import { Header } from "@/components/header";
import { Badge, Button, Card } from "@/components/ui";
import { expenses } from "@/lib/data";
import { rupiah } from "@/lib/utils";
import { ArrowDownLeft, ArrowUpRight, FileScan, Landmark, Plus, Sparkles, Upload } from "lucide-react";

export default function FinancePage() {
  return <><Header title="Keuangan" subtitle="Pantau arus kas, pendapatan, dan pengeluaran GrowthHive."/><section className="grid gap-4 md:grid-cols-3">{[{ l: "Total Pendapatan", v: rupiah(34000000), d: "+12,4%", icon: ArrowDownLeft, color: "text-teal-700 bg-teal-50" }, { l: "Total Pengeluaran", v: rupiah(12800000), d: "-4,2%", icon: ArrowUpRight, color: "text-rose-700 bg-rose-50" }, { l: "Laba Bersih", v: rupiah(21200000), d: "Margin 62,3%", icon: Landmark, color: "text-sky-700 bg-sky-50" }].map(({l,v,d,icon:Icon,color}) => <Card className="p-5" key={l}><div className={`mb-5 grid h-11 w-11 place-items-center rounded-xl ${color}`}><Icon size={20}/></div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{l}</p><p className="mt-2 text-2xl font-black text-ink dark:text-white">{v}</p><p className="mt-2 text-xs font-bold text-teal-600">{d} bulan ini</p></Card>)}</section><section className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_1fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between p-5"><div><h2 className="font-black">Pengeluaran Terbaru</h2><p className="text-xs text-slate-400">Semua transaksi operasional</p></div><Button><Plus size={15}/>Catat Pengeluaran</Button></div><div>{expenses.map(e => <div key={e.description} className="flex items-center gap-4 border-t border-slate-100 px-5 py-4 dark:border-slate-800"><div className="grid h-10 w-10 place-items-center rounded-xl bg-rose-50 text-rose-600"><ArrowUpRight size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{e.description}</p><p className="text-xs text-slate-400">{e.date}</p></div><Badge tone="slate">{e.category}</Badge><p className="text-sm font-black text-rose-600">-{rupiah(e.amount)}</p></div>)}</div></Card><Card className="relative overflow-hidden p-6"><div className="absolute right-0 top-0 h-32 w-32 rounded-full bg-teal-100 blur-3xl dark:bg-teal-900"/><div className="relative"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-ink text-white dark:bg-teal-600"><Sparkles size={21}/></div><h2 className="mt-5 text-lg font-black text-ink dark:text-white">Analisis Rekening dengan AI</h2><p className="mt-2 text-sm leading-6 text-slate-400">Unggah rekening koran PDF atau CSV. Gemini akan membaca, mengategorikan, dan mencocokkan transaksi secara otomatis.</p><button className="mt-6 flex w-full flex-col items-center rounded-2xl border-2 border-dashed border-teal-200 bg-teal-50/50 p-7 text-center dark:border-teal-900 dark:bg-teal-950/30"><Upload size={22} className="text-teal-600"/><span className="mt-2 text-xs font-black text-teal-700">Pilih berkas rekening koran</span><span className="mt-1 text-[10px] text-slate-400">PDF atau CSV, maks. 10 MB</span></button><div className="mt-4 flex items-center gap-2 text-[10px] text-slate-400"><FileScan size={13}/>Data hanya disimpan di Supabase Storage</div></div></Card></section></>;
}
