import { Header } from "@/components/header";
import { Button, Card } from "@/components/ui";
import { rupiah } from "@/lib/utils";
import { Download, TrendingUp } from "lucide-react";

const rows = [{ label: "Pendapatan invoice", amount: 34000000 }, { label: "Pendapatan lainnya", amount: 3500000 }, { label: "Team Salary", amount: -8500000 }, { label: "Tools & Subscriptions", amount: -2450000 }, { label: "Operational", amount: -1850000 }];
export default function ReportsPage() {
  return <><Header title="Laporan Keuangan" subtitle="Analisis performa dan kesehatan finansial bisnis."/><div className="mb-5 flex justify-end"><Button variant="outline"><Download size={15}/>Ekspor PDF</Button></div><section className="grid gap-4 md:grid-cols-3"><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Total Revenue</p><p className="mt-3 text-2xl font-black">{rupiah(37500000)}</p><p className="mt-2 text-xs font-bold text-teal-600">+14,8% dari bulan lalu</p></Card><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Total Expenses</p><p className="mt-3 text-2xl font-black">{rupiah(12800000)}</p><p className="mt-2 text-xs text-slate-400">34,1% dari pendapatan</p></Card><Card className="bg-ink p-5 text-white dark:bg-teal-800"><p className="text-xs font-bold uppercase tracking-wider text-teal-200">Net Profit</p><p className="mt-3 text-2xl font-black">{rupiah(24700000)}</p><p className="mt-2 flex items-center gap-1 text-xs font-bold text-teal-200"><TrendingUp size={13}/>Margin 65,9%</p></Card></section><Card className="mt-5 p-6"><div className="mb-6"><h2 className="font-black">Profit & Loss</h2><p className="text-xs text-slate-400">Periode Juni 2026</p></div><div className="space-y-1">{rows.map(r => <div key={r.label} className="flex justify-between border-b border-slate-100 py-4 text-sm dark:border-slate-800"><span className="font-semibold">{r.label}</span><span className={r.amount < 0 ? "font-black text-rose-600" : "font-black text-teal-700"}>{r.amount < 0 ? "-" : ""}{rupiah(Math.abs(r.amount))}</span></div>)}<div className="mt-4 flex justify-between rounded-xl bg-teal-50 p-4 font-black text-teal-800 dark:bg-teal-900/30 dark:text-teal-200"><span>Laba Bersih</span><span>{rupiah(24700000)}</span></div></div></Card></>;
}
