"use client";
import { getClientProjects, getClientValue, stages, type Client } from "@/lib/data";
import { rupiah } from "@/lib/utils";
import { Badge } from "./ui";
import { GripVertical } from "lucide-react";

export function Kanban({ clients, onMove }: { clients: Client[]; onMove: (id: string, stage: Client["stage"]) => void }) {
  return <div className="flex gap-4 overflow-x-auto pb-4">{stages.map(stage => { const items = clients.filter(c => c.stage === stage); return <div key={stage} onDragOver={e => e.preventDefault()} onDrop={e => onMove(e.dataTransfer.getData("id"), stage)} className="min-h-56 w-[284px] shrink-0 rounded-2xl bg-slate-100/70 p-3 dark:bg-slate-900"><div className="mb-3 flex items-center gap-2 px-1"><span className="h-2 w-2 rounded-full bg-teal-500"/><h3 className="text-xs font-black">{stage}</h3><span className="rounded-full bg-white px-2 py-0.5 text-[10px] font-bold text-slate-400 dark:bg-slate-800">{items.length}</span></div><div className="space-y-3">{items.map(client => <article draggable onDragStart={e => e.dataTransfer.setData("id", client.id)} key={client.id} className="cursor-grab rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex justify-between"><div><h4 className="text-sm font-black text-ink dark:text-white">{client.brand}</h4><p className="mt-1 text-[11px] text-slate-400">{client.industry} · {client.pic}</p></div><GripVertical size={14} className="text-slate-300"/></div><div className="mt-4"><Badge tone="slate">{getClientProjects(client).map(project => project.name).join(", ") || "Belum ada project"}</Badge></div><p className="mt-4 border-t border-slate-100 pt-3 text-xs font-black text-teal-700 dark:border-slate-800">{getClientValue(client) ? rupiah(getClientValue(client)) : "Retainer belum ditentukan"}</p></article>)}</div></div>})}</div>;
}
