"use client";
import { clients as seedClients, stages } from "@/lib/data";
import { rupiah } from "@/lib/utils";
import { Badge } from "./ui";
import { CalendarDays, GripVertical, MessageCircle } from "lucide-react";
import { useState } from "react";

export function Kanban() {
  const [clients, setClients] = useState(seedClients.map(c => ({ ...c, stage: c.stage as string })));
  return <div className="flex gap-4 overflow-x-auto pb-4">{stages.map(stage => { const items = clients.filter(c => c.stage === stage); return <div key={stage} onDragOver={e => e.preventDefault()} onDrop={e => { const id = e.dataTransfer.getData("id"); setClients(prev => prev.map(c => c.id === id ? { ...c, stage } : c)); }} className="w-[284px] shrink-0 rounded-2xl bg-slate-100/70 p-3 dark:bg-slate-900"><div className="mb-3 flex items-center justify-between px-1"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-teal-500"/><h3 className="text-xs font-black">{stage}</h3><span className="rounded-full bg-white px-2 py-0.5 text-[10px] font-bold text-slate-400 dark:bg-slate-800">{items.length}</span></div><span className="text-lg text-slate-300">+</span></div><div className="space-y-3">{items.map(client => <article draggable onDragStart={e => e.dataTransfer.setData("id", client.id)} key={client.id} className="cursor-grab rounded-xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-slate-800 dark:bg-slate-950"><div className="flex items-start gap-3"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl text-xs font-black ${client.color}`}>{client.initials}</div><div className="min-w-0 flex-1"><div className="flex justify-between"><h4 className="truncate text-sm font-black text-ink dark:text-white">{client.brand}</h4><GripVertical size={14} className="text-slate-300"/></div><p className="mt-0.5 text-[11px] text-slate-400">{client.industry} · {client.pic}</p></div></div><div className="mt-4 flex flex-wrap gap-1.5"><Badge tone="slate">{client.service}</Badge></div><div className="mt-4 flex items-end justify-between border-t border-slate-100 pt-3 dark:border-slate-800"><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Nilai Retainer</p><p className="mt-1 text-xs font-black text-teal-700">{client.value ? rupiah(client.value) : "Belum ditentukan"}</p></div><div className="flex gap-2 text-slate-300"><MessageCircle size={14}/><CalendarDays size={14}/></div></div></article>)}</div></div>})}</div>;
}
