"use client";
import { Header } from "@/components/header";
import { Button, Card } from "@/components/ui";
import { FormEvent, useState } from "react";
export default function SettingsPage() {
  const [saved, setSaved] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); localStorage.setItem("gh-company-settings", JSON.stringify(values)); setSaved(true); setTimeout(()=>setSaved(false), 2500); }
  function resetData() { if (!window.confirm("Hapus seluruh data lokal CRM, Project Hub, invoice, dan keuangan?")) return; ["gh-clients","gh-managed-clients","gh-project-tasks-v1","gh-daily-work-plans-v1","gh-calendar-events-v1","gh-team-members-v1","gh-project-tasks-v2","gh-daily-work-plans-v2","gh-calendar-events-v2","gh-team-members-v2","gh-project-tasks-v3","gh-team-members-v3","gh-invoices","gh-expenses"].forEach(key => localStorage.removeItem(key)); window.location.reload(); }
  return <><Header title="Pengaturan" subtitle="Kelola profil perusahaan, tim, dan integrasi."/><Card className="max-w-3xl p-6"><h2 className="font-black">Profil Perusahaan</h2><form onSubmit={submit}><div className="mt-6 grid gap-4 md:grid-cols-2">{["Nama perusahaan","Email","Nomor telepon","Alamat"].map((x,i) => <label key={x} className={i === 3 ? "md:col-span-2" : ""}><span className="mb-2 block text-xs font-bold text-slate-500">{x}</span><input name={["company","email","phone","address"][i]} className="h-11 w-full rounded-xl border border-slate-200 bg-transparent px-3 text-sm outline-none focus:border-teal-500 dark:border-slate-700" defaultValue={["PT. Growth Hive Indonesia","growthiveofficial@gmail.com","0881-0824-87487","APL Tower Central Park Lt. 26 T3, Jakarta 11470"][i]}/></label>)}</div><div className="mt-6 flex items-center gap-3"><Button>Simpan Perubahan</Button>{saved && <span className="text-xs font-bold text-teal-600">Pengaturan tersimpan.</span>}</div></form></Card><Card className="mt-5 max-w-3xl border-red-100 p-6"><h2 className="font-black text-red-700">Data Lokal</h2><p className="mt-2 text-sm text-slate-400">Gunakan ini untuk mengosongkan data sementara sebelum integrasi Supabase aktif.</p><Button type="button" variant="outline" onClick={resetData} className="mt-5 border-red-200 text-red-700">Hapus Seluruh Data Lokal</Button></Card></>;
}
