import { Header } from "@/components/header";
import { Badge, Button, Card } from "@/components/ui";
import { invoices } from "@/lib/data";
import { rupiah } from "@/lib/utils";
import { CircleDollarSign, Clock3, FileText, Filter, MoreHorizontal, Plus } from "lucide-react";
import dynamic from "next/dynamic";
const InvoiceDownload = dynamic(() => import("@/components/invoice-pdf").then(m => m.InvoiceDownload), { ssr: false });

export default function InvoicesPage() {
  return <><Header title="Invoice" subtitle="Buat, kirim, dan pantau pembayaran invoice."/><div className="mb-5 flex justify-end gap-2"><Button variant="outline"><Filter size={15}/>Filter</Button><Button><Plus size={16}/>Buat Invoice</Button></div><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[{ l: "Total Invoice", v: rupiah(67500000), i: FileText }, { l: "Sudah Terbayar", v: rupiah(34000000), i: CircleDollarSign }, { l: "Belum Terbayar", v: rupiah(33500000), i: Clock3 }, { l: "Jatuh Tempo", v: "1 Invoice", i: Clock3 }].map(({ l,v,i:Icon }) => <Card className="p-5" key={l}><div className="mb-4 grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon size={19}/></div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{l}</p><p className="mt-2 text-xl font-black text-ink dark:text-white">{v}</p></Card>)}</section><Card className="mt-5 overflow-hidden"><div className="flex items-center justify-between p-5"><div><h2 className="font-black">Semua Invoice</h2><p className="text-xs text-slate-400">Juni 2026</p></div><InvoiceDownload/></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400 dark:bg-slate-800/50"><tr>{["Nomor Invoice","Klien","Dibuat","Jatuh Tempo","Jumlah","Status",""].map(x => <th className="px-5 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{invoices.map(i => <tr className="border-t border-slate-100 dark:border-slate-800" key={i.no}><td className="px-5 py-4 font-bold text-teal-700">{i.no}</td><td className="px-5 py-4 font-semibold">{i.client}</td><td className="px-5 py-4 text-slate-500">{i.date}</td><td className="px-5 py-4 text-slate-500">{i.due}</td><td className="px-5 py-4 font-bold">{rupiah(i.amount)}</td><td className="px-5 py-4"><Badge tone={i.status === "Lunas" ? "teal" : i.status === "Jatuh Tempo" ? "red" : "amber"}>{i.status}</Badge></td><td><MoreHorizontal size={16}/></td></tr>)}</tbody></table></div></Card></>;
}
